bot:
    token: 'token' #token dostępu do bota
    prefix: '*'
    name: 'botname'
    adminrank: 123 #id rangi, którą posiada administracja
    channel_member_count: 123 #id kanału, który ma nosić nazwę z liczbą użytkowników
    channel_new_user: 123 #id kanału, który ma nosić nazwę z najnowszym użytkownikiem
    embed_color: 0xb4e1ff #tutaj wpisz kolor, jaki mają posiadać wiadomości typu embed
    synchro_rank: 123 #ranga, którą otrzymuje połączone konto z grą
mta:
    ip: '137.74.7.181' #ip serwera mta
    port: 22110 #port serwera mta
mysql:
    host: '' #host bazy danych
    user: '' #uzytkownik do bazy danych
    password: '' #haslo bazy danych
    database: '' #baza danych


