bot:
    token: 'token_here' #token dostępu do bota
    prefix: '*'
    name: 'botname'
    adminrank: 123 #id rangi, którą posiada administracja
    channel_member_count: 123 #id kanału, który ma nosić nazwę z liczbą użytkowników
    channel_new_user: 123 #id kanału, który ma nosić nazwę z najnowszym użytkownikiem
mta:
    ip: '149.202.65.66' #ip serwera mta
    port: 22003 #port serwera mta